### ISSUE TITLE
running on Windows

### ISSUE THREAD

**Issue by jillson** [jumanjiman/docker-xrdp#4]
I can do a pull request to update the documentaiton if that's easier/better, but in a nutshell:

running docker run -d -p 3389:3389 jumanjiman/xrdp on Windows, I can't connect (I get an error about session already open, which is presumably because there's a Windows RDP session available for remote help etc.).

Doing docker run -d -p 5000:3389 jumanjiman/xrdp, and then pointing my RDP client at 127.0.0.1:5000 works as expected

**Comment by jumanjiman** [comment]
a PR would be awesome. Can you also include a blurb about how you run it on windows? e.g., i imagine you use the hyper-v containers to get a linux kernel.

thank you!

**Comment by jillson** [comment]
PR submitted.  As far as running on Windows: there are basically two ways to run docker[1]: Windows Home (and I think WIndows 7 Home/Pro) can run Docker Toolbox, which works by basically running Virtualbox hidden behind the scenes; Windows Pro versions can take advantage Docker for Windows, which uses  Hyper-V (at the cost of losing the ability to run Virtualbox), and that's what I tested against.  I pretty much just ran the same commands you did (e.g. docker pull jumanjiman/xrdp and then docker run) 

Next up: use docker compose to spin up a server and client VM and see how bad the latency is for the client.

[1] (Arguably there's also the option to run VmWare/Virtualbox/Another Linux Virtualization Option, and then just run Docker inside your Linux VM which is effectively what Docker Toolbox does, but that's not as seamless as the above two)
